#!/bin/bash

set -e

if [[ ! -f /usr/bin/kreadconfig ]]
then
    ln -s /usr/bin/kreadconfig5 /usr/bin/kreadconfig
fi

if [[ ! -f /usr/share/applications/org.kde.discover.desktop ]]
then
    ln -s /usr/share/applications/mintinstall.desktop /usr/share/applications/org.kde.discover.desktop
fi

if [[ ! -f /usr/share/applications/org.kde.discover.apt.urlhandler.desktop ]]
then
    ln -s /usr/share/applications/mintinstall.desktop /usr/share/applications/org.kde.discover.apt.urlhandler.desktop
fi

sed -e '/NotShowIn/ s/^#*/#/' -i file /usr/share/applications/gdebi.desktop  || true